version: '3.7'
services:
 
  explorer:
    container_name: explorer
    image: binaries
    build: 
       context: binaries
    stdin_open: true
    working_dir: /home/docker/explorer
    command: bash -c "sudo ./safex-explorer -b /home/docker/.safex/lmdb -d http://daemon:17402 --bind-host 0.0.0.0 --enable-autorefresh-option 1 --no-blocks-on-index 20"
    restart: on-failure
    volumes:
      - /home/.safex:/home/docker/.safex
    depends_on:
      - daemon
    expose:
      - 8081

  daemon:
    container_name: daemon
    image: binaries
    build: 
       context: binaries
    working_dir: /home/docker/daemon
    command: bash -c "sudo ./safexd --rpc-bind-ip 0.0.0.0 --out-peers=20 --data-dir=/home/docker/.safex --confirm-external-bind --restricted-rpc"
    tty: true
    volumes:
      - /home/.safex:/home/docker/.safex
    expose:
      - 17402

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./styling/images:/usr/share/nginx/html/images
      - ./styling/css:/usr/share/nginx/html/css
      - ./styling/favicon.png:/usr/share/nginx/html/favicon.png
    depends_on:
      - explorer
    ports:
      - 8000:8000

networks:
  default:
    name: safex